[tox]
envlist = py311, py312, py313, flake8

[testenv:flake8]
basepython = python
deps = flake8
commands = flake8 geodecision

[testenv]
package = wheel
setenv =
    PYTHONPATH = {toxinidir}
dependency_groups =
    dev
commands =
    pytest --basetemp={envtmpdir}

